//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetDayService.Client.DayTellerService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DayTellerService.IDayTeller")]
    public interface IDayTeller {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDayTeller/GetDayFromDate", ReplyAction="http://tempuri.org/IDayTeller/GetDayFromDateResponse")]
        string GetDayFromDate(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDayTeller/GetDayFromDate", ReplyAction="http://tempuri.org/IDayTeller/GetDayFromDateResponse")]
        System.Threading.Tasks.Task<string> GetDayFromDateAsync(System.DateTime date);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDayTellerChannel : GetDayService.Client.DayTellerService.IDayTeller, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DayTellerClient : System.ServiceModel.ClientBase<GetDayService.Client.DayTellerService.IDayTeller>, GetDayService.Client.DayTellerService.IDayTeller {
        
        public DayTellerClient() {
        }
        
        public DayTellerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DayTellerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DayTellerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DayTellerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetDayFromDate(System.DateTime date) {
            return base.Channel.GetDayFromDate(date);
        }
        
        public System.Threading.Tasks.Task<string> GetDayFromDateAsync(System.DateTime date) {
            return base.Channel.GetDayFromDateAsync(date);
        }
    }
}
